version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile_node
    tty: true
    environment:
      - NODE_ENV=production
    volumes:
    - ./:/usr/src/app
    command: sh -c "cd studyreact && yarn start"
    ports:
    - "3000:3000"
